<?xml version="1.0" encoding="utf-8"?><Database Name="VoteS" Class="VotesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=votes.database.windows.net;Initial Catalog=VoteS;User ID=suave_azure;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="VoteSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VoteResults" Member="VoteResults">
    <Type Name="VoteResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FeatureVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PositionInVote" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VoterId" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>