#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotesApp.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VoteS")]
	public partial class VotesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVoteResult(VoteResult instance);
    partial void UpdateVoteResult(VoteResult instance);
    partial void DeleteVoteResult(VoteResult instance);
    #endregion
		
		public VotesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VoteSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VotesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VotesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VotesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VotesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VoteResult> VoteResults
		{
			get
			{
				return this.GetTable<VoteResult>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VoteResults")]
	public partial class VoteResult : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private int _FeatureVersion;
		
		private int _PositionInVote;
		
		private string _VoterId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFeatureVersionChanging(int value);
    partial void OnFeatureVersionChanged();
    partial void OnPositionInVoteChanging(int value);
    partial void OnPositionInVoteChanged();
    partial void OnVoterIdChanging(string value);
    partial void OnVoterIdChanged();
    #endregion
		
		public VoteResult()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeatureVersion", DbType="Int NOT NULL")]
		public int FeatureVersion
		{
			get
			{
				return this._FeatureVersion;
			}
			set
			{
				if ((this._FeatureVersion != value))
				{
					this.OnFeatureVersionChanging(value);
					this.SendPropertyChanging();
					this._FeatureVersion = value;
					this.SendPropertyChanged("FeatureVersion");
					this.OnFeatureVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionInVote", DbType="Int NOT NULL")]
		public int PositionInVote
		{
			get
			{
				return this._PositionInVote;
			}
			set
			{
				if ((this._PositionInVote != value))
				{
					this.OnPositionInVoteChanging(value);
					this.SendPropertyChanging();
					this._PositionInVote = value;
					this.SendPropertyChanged("PositionInVote");
					this.OnPositionInVoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VoterId", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string VoterId
		{
			get
			{
				return this._VoterId;
			}
			set
			{
				if ((this._VoterId != value))
				{
					this.OnVoterIdChanging(value);
					this.SendPropertyChanging();
					this._VoterId = value;
					this.SendPropertyChanged("VoterId");
					this.OnVoterIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
